FROM golang:1.21-alpine as builder

RUN apk add --no-cache git

WORKDIR /server

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go install github.com/cosmtrek/air@latest

ENV CONFIG_PATH=/server/local.yml

CMD ["air", "-c", ".air.toml"]